version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: lms_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: lmsdb
    ports:
      - "5432:5432"
    networks:
      - lms_network
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: lms_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - db
    networks:
      - lms_network

  frontend:
    build: ./rostack-frontend
    container_name: lms_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - lms_network

volumes:
  db_data:

networks:
  lms_network:
    driver: bridge
